AppBundle\Entity\ApiUser:
    type: entity
    table: api_user
    repositoryClass: AppBundle\Entity\ApiUserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        givenName:
            type: string
            nullable: true
            column: given_name
        familyName:
            type: string
            nullable: true
            column: family_name
        telephone:
            type: phone_number
            nullable: true
        facebookId:
            type: string
            nullable: true
            column: facebook_id
        facebookAccessToken:
            type: string
            nullable: true
            column: facebook_access_token
    oneToMany:
        remotePushTokens:
            targetEntity: AppBundle\Entity\RemotePushToken
            mappedBy: user
        reusablePackagingUnits:
            targetEntity: AppBundle\Entity\ReusablePackaging\Unit
            mappedBy: user
            cascade:
                - all
    manyToOne:
        channel:
            targetEntity: Sylius\Component\Channel\Model\ChannelInterface
            joinColumns:
                channel_id:
                    referencedColumnName: id
                    nullable: true
    manyToMany:
        restaurants:
            targetEntity: AppBundle\Entity\Restaurant
            inversedBy: owners
            cascade:
                - all
            fetch: LAZY
            joinTable:
                name: api_user_restaurant
                inverseJoinColumns:
                    -
                        name: restaurant_id
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
                joinColumns:
                    -
                        name: api_user_id
                        referencedColumnName: id
                        onDelete: CASCADE
            orderBy: null
        stores:
            targetEntity: AppBundle\Entity\Store
            inversedBy: owners
            cascade:
                - all
            fetch: LAZY
            joinTable:
                name: api_user_store
                inverseJoinColumns:
                    -
                        name: store_id
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
                joinColumns:
                    -
                        name: api_user_id
                        referencedColumnName: id
                        onDelete: CASCADE
            orderBy: null
        addresses:
            targetEntity: AppBundle\Entity\Address
            cascade:
                - all
            fetch: LAZY
            joinTable:
                name: api_user_address
                inverseJoinColumns:
                    -
                        name: address_id
                        unique: false
                        nullable: true
                        onDelete: null
                        columnDefinition: null
                        referencedColumnName: id
                joinColumns:
                    -
                        name: api_user_id
                        referencedColumnName: id
                        onDelete: CASCADE
            orderBy: null
        stripeAccounts:
            targetEntity: AppBundle\Entity\StripeAccount
            cascade:
                - all
            joinTable:
                name: api_user_stripe_account
                joinColumns:
                    - name: user_id
                      referencedColumnName: id
                inverseJoinColumns:
                    - name: stripe_account_id
                      referencedColumnName: id
                      onDelete: CASCADE
